[package]
authors = ["Jonathan 'theJPster' Pallant <github@thejpster.org.uk>"]
edition = "2018"
resolver = "2"
readme = "README.md"
license = "GPL-3.0-or-later"
name = "neotron-pico-bios"
version = "0.2.0"

[dependencies]
# Useful Cortex-M specific functions (e.g. SysTick)
cortex-m = "0.7"
# The Raspberry Pi Pico HAL
# pico = { git = "https://github.com/rp-rs/rp-hal.git" }
pico = { path = "/home/jonathan/Documents/rp-rs/rp-hal/boards/pico" }
# Cortex-M run-time (or start-up) code
cortex-m-rt = "0.7"
# The BIOS API we export to the OS
neotron-common-bios = { git = "https://github.com/Neotron-Compute/Neotron-Common-BIOS.git" }
# For time keeping/handling
embedded-time = "0.12"
# For the RP2040 bootloader
rp2040-boot2 = "0.1"
# For hardware abstraction traits
embedded-hal ="0.2"
# Gives us formatted PC-side logging
defmt = "0.2"
# Sends defmt logs to the SWD debugger
defmt-rtt = "0.2"
# Send panics to the debugger
panic-probe = "0.2"
# Fetches the BIOS version from git
git-version = "0.3"
# RP2040 PIO driver
pio = { git = "https://github.com/rp-rs/pio-rs.git", branch = "main" }
# RP2040 PIO driver macros
pio-proc = { git = "https://github.com/rp-rs/pio-rs.git", branch = "main" }

[features]
default = [
    "defmt-default",
]
defmt-default = []
# Enables trace logs
defmt-trace = []
# Enables debug logs
defmt-debug = []
# Enables info logs
defmt-info = []
# Enables warn logs
defmt-warn = []
# Enables error logs
defmt-error = []

[[bin]]
name = "neotron-pico-bios"
test = false
bench = false

[profile.release]
# better optimizations
codegen-units = 1
# symbols are nice and they don't increase the size on Flash
debug = true
# better optimizations
lto = true

[patch.crates-io]
rp2040-pac = { path = "/home/jonathan/Documents/rp-rs/rp2040-pac" }
